### ISSUE TITLE
Abwesenheit wird nicht angezeigt/getriggert

### ISSUE THREAD

**Issue by lahlor** [mcbeyel/IPSLocative#1]
Hallo,

leider wird bei mir der Wert Exit nie auf Abwesend gestellt, obwohl ich nicht mehr zu Hause bin. Location muss aber funktionieren, da die ganzen Werte automatisch in IPS erstellt wurden. Jedoch wurde bislang nie der Wert "Timestamp" aktualisiert bzw. er enthält keine Daten. Muss das so sein?
Wo kann ich prüfen, welches Problem das Modul hat? Die URL´s rufe ich über die Connect URL auf, die immer erreichbar ist. Mir ist noch aufgefallen, dass die URL bei dir aus dem Readme falsch ist. Es muss  http://your IP Symcon IP:your IP Symcon port/hook/locative?status=arrival heissen und nicht location, da ich sonst keinen passenden "Hook" habe.
Ich wäre um jede Hilfe dankbar.

Gruß
lahlor

**Comment by tbeyel** [comment]
Hi,

ja die URL ist falsch, das muss ich korrigieren. Ich habe aber bereits ein Update gestern veröffentlicht. Bitte probiere es damit einmal. (In IP-Symcon sollte das Modul geupdatet werden können)

**Comment by lahlor** [comment]
Hi,

das Update hatte ich heute morgen eingespielt, aber leider keine Veränderung. Wie kann ich denn den Zustand "neu triggern"? Ich befinde mich gerade nicht zu Hause, sodass er auch nach dem Update eigentlich auf Abwesend springen sollte. Wie oft triggert denn die App den Wert zum IPS Server?

**Comment by lahlor** [comment]
Du hast die Readme auch angepasst. Nun soll nur folgender Link für beides in die App eingetragen werden http://your IP Symcon IP:your IP Symcon port/hook/locative
Soll also kein status mehr mitgegeben werden? Erhalte außerdem nach dem Update folgenden Fehler
25.01.2016 08:32:13 | InstanceManager | <br />
<b>Parse error</b>:  syntax error, unexpected ')' in <b>C:\IP-Symcon\modules\IPSLocative\Module\module.php</b> on line <b>87</b><br />

**Comment by tbeyel** [comment]
Der Status ist nicht erforderlich, weil die App einen "trigger" sendet "enter" und "exit". 

Leider kann man den Status nicht manuell auslösen in der App, wäre schön wenn man das könnte. Den Fehler im Modul habe ich gerade gefixt, ich hatte leider eine falsche Version comittet.

**Comment by lahlor** [comment]
ok danke. Wenn ich auf die Meldung klicke, springt er direkt in die Locative Instanz. Dort fehlte auf einmal der Benutzername und das Kennwort. Wollte es dann nachträglich eintragen und erhalte erneut einen Fehler "Password array nicht gefunden". Ich habe das Modul komplett gelöscht und nach einem IPS restart neu hinzugefügt. Da ich den Trigger nicht auslösen kann, muss ich nun entsprechend warten bis die App den Trigger selbst ausführt. Dann sollten sich die Werte ja auch wieder eintragen und dann schauen wir mal, ob es nun vielliecht klappt.

**Comment by tbeyel** [comment]
Man kann nun über die Testfunktion einen Trigger simulieren, indem man in den Einstellungen der Locative-App als URL z.B ../?name=TEST&status=1 verwendet.

"name" enthält den Namen des Bereichs, der den Trigger ausgelöst hat. Die Variable in IP-Symcon erhält den gleichen Namen. Dies ist notwendig, da Locative den Namen des Bereichs nicht mitsendet....leider.
"status" simuliert entsprechend An- bzw. Abwesenheit

Außerdem wird der Zeitstempel nun korrekt geparst.

**Comment by lahlor** [comment]
Vielen Dank für das Update. Leider scheint der Test nicht zu klappen. Erhalte ein 401 Unauthorized zurück aus der App. Habe auch den korrekten HTTP Auth mitgegeben. Nach deinem Update habe ich die Locative Instanz nochmals komplett gelöscht. Durch den Test sollte doch alle in IPS angelegt werden,  oder nicht?

**Comment by tbeyel** [comment]
Also ich erhalte keinen Unauthorized zurück. Du hast also in den Einstellungen direkt unterhalb des Tests ebenfalls die HTTP Basic Auth aktiviert? Und identische Daten für die Locative Instanz konfiguriert?

**Comment by lahlor** [comment]
ES KLAPPT! Ich hatte alles kontrolliert und nun einfach nochmal den User und Password im Modul neu eingetragen. Kennwort ist ein Buchstabe, daher Tippfehler unwahrscheinlich, aber es war wohl ein Tippfehler :) Ich danke vielmals!
